### ISSUE TITLE
math env should consume first line

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#77] opened 2020-08-09 07:37 UTC
```
$language=latexMath
V_i = C_0 - C_3
\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}
$
should not display language=latexMath

**Comment by kasperosterbye** [comment] 2021-09-13 08:36
I am not sure this is actually a bug. It seems like `$` is the symbol for inline math, whereas `&` is used for multiline math blocks. It is not clear one should be able to add parameters to an inline block.

And since `&` is used for math, it seems like it is unnecessary to specify `language=latexMath`.

**Comment by Ducasse** [comment] 2021-09-13 08:37
I do not remember normally we have tests. 
Check closeMe this is a hook for posttreament on block closure.

**Comment by kasperosterbye** [comment] 2021-09-13 08:53
The `MicMathInlineBlock>>closeMe` hook says
```smalltalk
closeMe 
	self flag: #back. "self halt"
```
So - the issue is left open to handle.

But in any case, if you want the above to succeed you must be able to tell the difference between `$language=latexMath stuff$` (where the `a=b` is an parameter) and `$foo=bar_2$` (which should be rendered as math).

From my reading of the code, I believe it is not an error, and the example works just right with `&` instead of `$` - as in:
```
&language=latexMath
V_i = C_0 - C_3
\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}
&
```

**Comment by Ducasse** [comment] 2021-09-13 18:49
Ah may be I was confused normally we have two markups 
- one for inline 
- one for environment

```
MicroDownParser inlineMarkups at: #math 
>>>
'$'
```

**Comment by Ducasse** [comment] 2021-09-13 18:50
```
MicrodownParser mathOpeningBlockMarkup
>>>
&
```

**Comment by Ducasse** [comment] 2021-09-13 18:52
in the example I put language but what we want in general is caption and anchor or parameters to be passed to the underlying Latex or mathJax library
```
&caption=A wonderful formula&anchor=formula33
V_i = C_0 - C_3
\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}
&
```

**Comment by Ducasse** [comment] 2021-09-13 18:54
The math environment should have 
- caption and anchor in the parameters dictionary of the environment
- note that caption may contain bold or wrapped text
- body the math body.

**Comment by Ducasse** [comment] 2021-09-13 18:54
Is my explanation clear?

**Comment by kasperosterbye** [comment] 2021-09-14 04:48
Indeed - this makes all sense.

**Comment by kasperosterbye** [comment] 2021-09-14 04:50
I suggest you just close this one - it boiled down to a $ which should have been an &.

**Closed** 2021-09-24 07:46 UTC
