### ISSUE TITLE
Package Microdown - HTML seems obsolete

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#627] opened 2022-11-07 06:40 UTC
It is not loaded in dev, and it seems like a preliminary version of the HTML exporter.
Should it be deleted?

**Comment by Ducasse** [comment] 2022-11-10 21:16
If it is an old version we should delete it.

**Comment by riuttner** [comment] 2024-08-23 10:56
Yesterday I started using it, because I need something to convert plain markdown (not using features that are not available in mic) to HTML, and it worked nicely in principal (tried Pharo12 branch), many thanks to the team for the whole work!

And of course I would appreciate if the HTML exporter will be continued!

When trying to run some examples around HTML, I ran into some strange issues (examples do not finish using CPU, and breaking shows code points around file error handling). For now I did not look deep, but it all seemed to be related to internal contradictions when accessing files (and unclear conditions what to expect where and to copy from and to, in this case concering CSS). Before I do more research in that area and open specific tickets, here my general question: Does it make sense to continue the work on the HTML exporter? Then I will of course also check my observations with other branches.

Some of the things I would like to implement for mic/markdown to HTML conversion is introducing a configuration entry for support of "auto-anchoring" of local headings (e.g. by adding an "id" attribute with a value derived from the heading text). This is especially important for pure markdown, because there local "#" references may contain utf8 letters which cannot be printed by the HTML stream writer, so HTML export for my purpose even needs to control and possibly rewrite all references. That would anyway make sense if there are explicit MD file references, because IMHO it should be possible to configure translation of the file types of links too, if going from MD to HTML.

Currently the generated example for mic to HTML translation does not work for links (because there is no anchor for the link specified). So if you open the file in a browser and click the link, it just jumps to the top of the page. I would also like to open an issue to talk about how to fix that, either by using mic features to define the missing anchor, or extending the example to also include "auto-anchoring" as mentioned above.

**Comment by Ducasse** [comment] 2024-08-23 16:35
Hi 

Please one problem in one issue. 
- Can you open specific issue if you have a reproducible case for the HTML because we used it a lot recently
- We were moving the CSS into ressources to not rely on external failure points (hernanmd should finish the logic to make sure that the tests run on the GH server).
- For the auto-anchoring develop a visitor in a package like that you can control it and we can later include it in a baseline. 

My goal for now is to finish the current log of action with the goal to have foliage running 100 % on top of microdown (and not converting to pillar).

**Comment by Ducasse** [comment] 2024-08-23 16:35
So I will close this issue because we have an HTML exporter and please open new issues.

**Closed by Ducasse** 2024-08-23 16:35 UTC
Labels: HTML
